- name: Install firewalld
  yum:
    name: firewalld
    state: latest
  notify:
      - start firewalld

- name: enable 80
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: yes
